//
//  CLITypes.swift
//  LiquidCLICore
//
//  Created as part of RhoeLiquid
//  A high-performance Swift implementation of the Liquid template language
//

import Foundation
import ArgumentParser

/// Errors specific to CLI operations.
enum CLIError: Error, CustomStringConvertible {
    case fileNotFound(String)
    case invalidFormat(String)
    case renderFailed(String)
    case directoryCreationFailed(String)

    var description: String {
        switch self {
        case .fileNotFound(let path): return "File not found: \(path)"
        case .invalidFormat(let msg): return "Invalid format: \(msg)"
        case .renderFailed(let msg): return "Render failed: \(msg)"
        case .directoryCreationFailed(let path): return "Could not create directory: \(path)"
        }
    }
}

/// Output format for analysis and reporting commands.
/// Output format for analysis reports.
public enum OutputFormat: String, CaseIterable, ExpressibleByArgument, Sendable {
    case terminal
    case json
    case markdown

    public init?(argument: String) {
        self.init(rawValue: argument)
    }

    static var completion: CompletionKind {
        .list(allCases.map(\.rawValue))
    }
}

/// Starter project shape generated by `liquid init`.
public enum ProjectType: String, CaseIterable, ExpressibleByArgument, Sendable {
    case simple
    case web
    case api
    case documentation

    public init?(argument: String) {
        self.init(rawValue: argument)
    }

    static var completion: CompletionKind {
        .list(allCases.map(\.rawValue))
    }
}

/// Metadata about a discovered template file.
struct TemplateInfo: Sendable {
    let path: String
    let name: String
    let size: Int

    init(path: String) throws {
        self.path = path
        self.name = (path as NSString).lastPathComponent
        let attrs = try FileManager.default.attributesOfItem(atPath: path)
        self.size = (attrs[.size] as? Int) ?? 0
    }
}

/// Loads context data from a JSON file path.
func loadContextData(from path: String) throws -> [String: Any] {
    let data = try Data(contentsOf: URL(fileURLWithPath: path))
    guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
        throw CLIError.invalidFormat("Context file must contain a JSON object (not array)")
    }
    return json
}

/// Discovers template files in a path (file or directory).
func discoverTemplates(at path: String, recursive: Bool = true) throws -> [TemplateInfo] {
    let fm = FileManager.default
    var isDir: ObjCBool = false
    guard fm.fileExists(atPath: path, isDirectory: &isDir) else {
        throw CLIError.fileNotFound(path)
    }

    if !isDir.boolValue {
        return [try TemplateInfo(path: path)]
    }

    let enumerator = fm.enumerator(
        at: URL(fileURLWithPath: path),
        includingPropertiesForKeys: [.isRegularFileKey],
        options: recursive ? [] : [.skipsSubdirectoryDescendants]
    )

    var templates: [TemplateInfo] = []
    while let url = enumerator?.nextObject() as? URL {
        if url.pathExtension == "liquid" || url.pathExtension == "html" {
            templates.append(try TemplateInfo(path: url.path))
        }
    }
    return templates.sorted { $0.path < $1.path }
}
